version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rallyon_db
      POSTGRES_USER: rallyon
      POSTGRES_PASSWORD: rallyon
    volumes:
      - ./rallyon-backend/src:/app/src
      - ./rallyon-backend/build.gradle:/app/build.gradle
      - ./rallyon-backend/settings.gradle:/app/settings.gradle
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./rallyon-backend
    container_name: rallyon_backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rallyon
      SPRING_DATASOURCE_USERNAME: rallyon
      SPRING_DATASOURCE_PASSWORD: rallyon
    ports:
      - "5005:5005"
    depends_on:
      - db

  frontend:
    build: ./rallyon-frontend
    container_name: rallyon_frontend_dev
    ports:
      - "5173:80"
    volumes:
      - ./rallyon-frontend:/app
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5005
    depends_on:
      - backend

volumes:
  postgres-data:
