version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rallyon
      POSTGRES_PASSWORD: rallyon
      POSTGRES_DB: rallyon_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rallyon-net

  backend:
    build: ./rallyon-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rallyon_db
      - SPRING_DATASOURCE_USERNAME=rallyon
      - SPRING_DATASOURCE_PASSWORD=rallyon
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - rallyon-net

  frontend:
    build: ./rallyon-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - rallyon-net

volumes:
  postgres-data:

networks:
  rallyon-net:
    driver: bridge

