spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rallyondb
    username: rallyon_dev
    password: rallyondev1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영 시에는 validate 또는 none 추천
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # 로컬 개발 시 포트 변경 가능
  server:
    port: 8080
