version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rallyon_db
    environment:
      POSTGRES_DB: rallyon
      POSTGRES_USER: rallyon
      POSTGRES_PASSWORD: rallyon
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: rallyon_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rallyon
      SPRING_DATASOURCE_USERNAME: rallyon
      SPRING_DATASOURCE_PASSWORD: rallyon
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: rallyon_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
